language: python
dist: trusty
branches:
  only:
  - master
addons:
  apt:
    packages:
    - pandoc
    - pandoc-citeproc
before_install:
- wget -O prepara_tesi.sh https://raw.githubusercontent.com/mrizzoli/pandoc_scripts/master/prepara_tesi.sh
- chmod +x prepara_tesi.sh
script:
- "./prepara_tesi.sh"
env:
  global:
  - secure: FZF6DDlN3TVPOc00hHznGRwa+JzhFiLEGHXw/nZJQ01hVpjWvl8GWtO4s2ftlNTOBtSiFVNMCMAv93m6yd+5ELGuQQDUNCFvBylsQ5nd1Iyrt23gxYNyY8L30nlgzGwSXSioa6bxyNFqmhy4GngWP4J1jFGy/IVGy2c2N66kF/gUM4+Q9bM3LX1a1Bhv0bsPyBtSr2GhHutI2wdVsTIwlOybhQXagUAFmJXACnNRvNmNlc94GOmFkiYbcVBv0bUfMdACof+zQEu/kzVzS+wlK3ZHHt/8nSSsRK56847Ku57kEqwuhFFLMDqkAnfG9Z36FPBc9dyEZBybj/dtqw+YvvQFhLDWirpK1sw4+wXOoQOjIU84Zz34hYJwhfNsgaWnv8GdZfucoxEwhJ0nQ6R4rQhGS83GCnSKBpQRPSWHOwIbMo4DJt623SwxPOJqFsM5IJ8tOK8qI+xMRTiPkHiVjBzW+ZK1r5OBaaCjte0S4s9UHkyHVXF0QaMcV6NQ+dZJvqPIqXaFvW36HyQceSV0FxR6DPSSno4MW/MnK5UtuksMCK/VS9NNHLwn3fFAEln82I5U3KrA4V4kl2mFeYyc0TcpvNjjfeX+WQVUMz19dBHRuJntExRZB2kGDmDPxfhykK56tEiuY5CB4Zj7Sdmv97aisPWM899oqwQsbevzjJA=
